language: node_js
services:
  - postgresql
before_script:
  - npm install -g gulp-cli
  - psql -c "CREATE DATABASE mbutest;" -U postgres
  - psql -c "CREATE USER mbu;" -U postgres
script: gulp test:api
